### ISSUE TITLE
README: Team Members

### ISSUE THREAD

**Issue by SeanAlling** [nijo-tan/EE-Emerge-2020-LightFight#1]
Team members listed in the README should be in the following format 

* **[John Smith](https://github.com/GITHUB_USERNAME)** - *Blank OR Role*

One entry per member. With the above the members name will be bulleted, Bold, and clicking on the name will let the user go to the members GitHib profile. 

The last element (seperated by a -), can be left blank or a team members role can be used, i.e. Team Leader, Professor, etc...

**Comment by derekeverhart** [comment]
check
